name: env_switch_demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_remote_config: ^2.0.13
  package_info_plus: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

flutter:

  uses-material-design: true

  assets:
    - assets/launcher_icon/icon-dev.png
    - assets/launcher_icon/icon-stage.png
    - assets/launcher_icon/icon-prod.png

flutter_icons:
  android: true
  ios: true
